# This is the configuration used to check the rubocop source code.

LineLength:
    Max: 119

# Just to avoid warning in metadata files.
SingleSpaceBeforeFirstArg:
    Enabled: false

# Avoid warning for digit (should be 12_345 but we don't care !)
NumericLiterals:
    Enabled: false
