source 'https://rubygems.org'

gem 'berkshelf', '~> 3.1'
gem 'chef'
gem 'chef-zero'
gem 'json'
gem 'kitchen-vagrant'
gem 'test-kitchen'
gem 'vagrant-berkshelf', '~> 2.0.0'
gem 'foodcritic'
gem 'serverspec'
gem 'chefspec'
gem 'rubocop'
gem 'jekyll'
gem 'kramdown'
gem 'bundler'
gem 'eventmachine'
gem 'thin'
gem 'nokogiri'
gem 'hitimes'
gem 'nio4r'
gem 'dep'
gem 'dep_selector'
